# Generated by Django 5.0.6 on 2024-06-24 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maison', models.CharField(max_length=100)),
                ('piece', models.CharField(max_length=100)),
                ('id_capteur', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'capteur',
            },
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('temperature', models.FloatField(max_length=100)),
                ('id_capteur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='domoticapp.capteur')),
            ],
            options={
                'db_table': 'donnee',
            },
        ),
    ]
